name: Code Review
on:
    push:
        branches: [ main ]  
    pull_request:
        branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
    - name: Run linter
      run: npm run linting
    - name: Run static code analysis
      run: npm run analyze
    - name: Authenticate Snyk
      run: npx snyk auth ${{ secrets.SNYK_TOKEN }}
    - name: Run security scan
      run: npm run security-check
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-review
        path: code-review/