name: Dependabot
on:
    push:
        branches: [ main ]  
    schedule:
        - cron: '0 0 * * *'
    pull_request:
        types: [opened, synchronize]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
    - name: Run Dependabot
      if: github.event_name == 'schedule' || github.event_name == 'push'
      uses: dependabot/dependabot-core@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        directory: '/'
        package-manager: 'npm'
        versioning-strategy: 'lockfile-only'
    - name: Run tests
      if: github.event_name == 'pull_request'
      run: npm run test