name: Scheduled Tasks

on:
    schedule:
        - cron: '0 12 * * *'

jobs:
  tasks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run script
    - run: npm run script1
    - run: npm run script2
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ./logs/*.log
    - name: Create Issue From Action
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issue = {owner: context.repo.owner, repo: context.repo.repo, title: "New Scheduled Task Run", body: "New scheduled tasks run has completed. Check the artifacts for the logs."}
          github.issues.create(issue)